spring.datasource.url=jdbc:mysql://localhost:3306/fpt_market?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
spring.application.name=fpt-market-server

jwt.secret=this_is_a_very_long_secret_key_for_fpt_market_jwt_signature
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
